# Generated by Django 6.1 on 2026-08-20 16:10

import apps.informes.storage_backends
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='CategoriaDano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de Daño',
                'verbose_name_plural': 'Tipos de Daño',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('domicilio', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='UsuarioTransportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Transportista',
                'verbose_name_plural': 'Transportistas',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('CAMION', 'Camión'), ('SEMIREMOLQUE', 'Semirremolque'), ('CAMIONETA', 'Camioneta'), ('FURGONETA', 'Furgoneta'), ('PARTICULAR', 'Particular')], default='CAMION', max_length=20)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
        migrations.CreateModel(
            name='InformeDano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_identificador', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Indentificador único del reporte para trazabilidad', unique=True)),
                ('remito_recepcion', models.CharField(error_messages={'unique': 'El número de remito ya se encuentra en el sistema.'}, max_length=100, unique=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes', to='informes.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes_creados', to='usuarios.empleado')),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes', to='informes.usuariotransportista')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes', to='informes.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piezas', to='informes.categoria')),
            ],
            options={
                'verbose_name': 'Pieza',
                'verbose_name_plural': 'Piezas',
            },
        ),
        migrations.CreateModel(
            name='PiezaRechazada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_identificador', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('imagen', models.ImageField(blank=True, null=True, storage=apps.informes.storage_backends.AzureMediaStorage(), upload_to='piezas-rechazadas-images/')),
                ('categoria_dano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piezas_rechazadas', to='informes.categoriadano')),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piezas_rechazadas', to='informes.informedano')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piezas_rechazadas', to='informes.pieza')),
            ],
        ),
    ]
