name: Encender y Apagar Render

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * 1-5'
    - cron: '0 20 * * 1-5'

jobs:
  manejar-servidor-render:
    runs-on: ubuntu-latest
    steps:
      - name: Determinar Acción (Encender o Apagar)
        id: definir_accion
        run: |
          # Obtenemos la hora en formato UTC
          HORA_UTC=$(date -u +%H)
          
          # Si son las 11 UTC (8 AM Argentina), la acción es 'resume'
          if [ "$HORA_UTC" -eq "11" ]; then
            echo "ACCION=resume" >> $GITHUB_ENV
            echo "Es hora de encender el servidor."
          else
            # Si no, la acción es 'suspend'
            echo "ACCION=suspend" >> $GITHUB_ENV
            echo "Es hora de apagar el servidor."
          fi

      - name: Enviar comando a la API de Render
        run: |
          curl --request POST \
            --url "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/${{ env.ACCION }}" \
            --header 'accept: application/json' \
            --header "authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
